server:
  port: 9001

spring:
  application:
    name: admin-server

eureka:
  instance:
    hostname: admin-server
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'