server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: path_user #转发
          uri: lb://user #lb:从注册中心获取服务 user:转发的服务名称（这个服务名称必须和eureka中对应）
          predicates:
            - Path=/user/**
#          filters:
#            - AddRequestHeader=test,test #符合匹配规则后，添加请求头，传递到后端
#            - RemoveRequestHeader=test,test #符合匹配规则后，删除请求头
#            #AddRequestParameter,AddResponseHeader,AddResponseHeader
#            #RedirectTo=302, http://baidu.com 重定向
#        - id: path_product
#          uri: lb://product
#          predicates:
#            - Path=/product/**
#          #Query=foo,ba. 参数匹配?foo=baz。
#          #Method=Get   HTTP方法匹配
#          #Header=Content-type,Application/json Header匹配
      discovery:
        locator:
          lower-case-service-id: true #服务名转小写
          enabled: true #根据服务名称serviceId转发
      #cros跨域
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            exposedHeaders:
              - content-type
            allowedHeaders:
              - content-type
            allowCredentials: true
            allowedMethods:
              - GET
              - OPTIONS
              - PUT
              - DELETE
              - POST

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway