server:
  port: 9002
spring:
  application:
    name: turbine-server
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /

eureka:
  instance:
    hostname: turbine-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

#普通模式
#    cluster-config: main
#  app-config: user,product
#  cluster-name-expression: metadata['cluster']

hystrix:
  dashboard:
    proxy-stream-allow-list: "127.0.0.1"
management:
  endpoints:
    web:
      exposure:
        include: '*'
