server:
  port: 9004

spring:
  application:
    name: zipkin-server

eureka:
  instance:
    hostname: zipkin-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/