server:
  port: 8761

spring:
  profiles: cluster1
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false #该值若配置一定要配置为false! 代表使用IP地址的形式来定义注册中心的地址，而不使用主机名，而defaultZone中是以域名的方式向注册中心注册的，最终导致分片节点不能识别匹配（IP地址与域名），而认为分片均处于不可达状态。
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false # 自我保护机制 生产环境开启true
    eviction-interval-timer-in-ms: 15000
    renewal-threshold-update-interval-ms: 10000
    renewal-percent-threshold: 0.45
