server:
  port: 8762

spring:
  profiles: cluster2
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false # 自我保护机制 生产环境开启true
    eviction-interval-timer-in-ms: 15000
    renewal-threshold-update-interval-ms: 10000
    renewal-percent-threshold: 0.45
management:
  endpoints:
    web:
      exposure:
        include: '*'
