server:
  port: 9003
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.dir}/config-repo #classpath:/config-repo

  profiles:
    active: native

eureka:
  client:
    service-url:
      default: http://peer:8761/eureka/,http://peer:8761/eureka/
  instance:
    hostname: config-server
    prefer-ip-address: true
