server:
  port: 8081

spring:
  application:
    name: product
  ### 消息队列
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /

  cloud:
    stream:
      bindings:
        myMessageOut:
          destination: product-my-message
          producer:
            partition-key-expression: headers["unique"] #消息分区唯一性标识
            partition-count: 2 #消息分区的数量
        myMessageIn:
          destination: product-my-message #绑定的交换名称 一个交换机有一个队列绑定
          group: group-product-my-message #同一个组存在资源竞争 只有一个队列可以获取消息；不同的组不存在竞争
          #消息分组 解决一条消息被一个消费者消费  消息分区 解决重复发送消息
          consumer:
            partitioned: true
      instance-count: 2 #分区总数
      instance-index: 0 #索引


eureka:
  instance:
    hostname: product
    prefer-ip-address: true
    metadata-map:
      cluster: main
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
