server:
  port: 8081

spring:
  application:
    name: product
  ### 消息队列
  rabbitmq:
    host: localhost
    username: admin
    password: admin

eureka:
  instance:
    hostname: product
    prefer-ip-address: true
    metadata-map:
      cluster: main
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
